create table if not exists public.dooms_waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text,
  source text not null default 'dooms-page',
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dooms_waitlist_joined_at_idx
  on public.dooms_waitlist (joined_at desc);

alter table public.dooms_waitlist enable row level security;

drop policy if exists "dooms_waitlist_service_role_all" on public.dooms_waitlist;
create policy "dooms_waitlist_service_role_all"
on public.dooms_waitlist
for all
to service_role
using (true)
with check (true);

grant insert, select, update, delete on public.dooms_waitlist to service_role;
grant usage, select on sequence public.dooms_waitlist_id_seq to service_role;
