create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  is_active boolean not null default true,
  subscribed_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists newsletter_subscribers_is_active_idx
  on public.newsletter_subscribers (is_active);

create table if not exists public.newsletter_dispatch_state (
  id smallint primary key,
  last_sent_devto_article_id bigint,
  last_sent_at timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.newsletter_dispatch_state (id)
values (1)
on conflict (id) do nothing;

